name: DNS Resolver

on:
  schedule:
    - cron: '0 0 * * *'   # Every day at 00:00 UTC
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Allows committing changes

jobs:
  resolve-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Use manual token handling

      - name: Install dig (dnsutils)
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      - name: Resolve all IPs and update file
        run: |
          echo "Rebuilding resolved_ips.txt..."
          > resolved_ips.txt
          while IFS= read -r domain; do
            if [[ -z "$domain" || "$domain" == \#* ]]; then
              continue
            fi
            echo "# $domain" >> resolved_ips.txt
            dig +short "$domain" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' >> resolved_ips.txt
            echo "# end $domain" >> resolved_ips.txt
            echo >> resolved_ips.txt
          done < domains.txt
          cat resolved_ips.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add resolved_ips.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated resolved IPs on $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
